export const HIDE_GENERATE_BUTTON = 'HIDE_REGENERATE_BUTTON';
export const SHOW_REGENERATE_BUTTON = 'SHOW_REGENERATE_BUTTON';
export const SHOW_STOP_GENERATION_BUTTON = 'SHOW_STOP_GENERATION_BUTTON';
