export const EVENT_SEND_MESSAGE = 'EVENT_SEND_MESSAGE';
export const EVENT_MESSAGE_DOING = 'EVENT_MESSAGE_DOING';
export const EVENT_GET_LOGIN_SESSION = 'EVENT_GET_LOGIN_SESSION';
export const EVENT_SET_CONFIG = 'EVENT_SET_CONFIG';
export const EVENT_GET_CONFIG = 'EVENT_GET_CONFIG';

export const EVENT_GET_PROMPT = 'EVENT_GET_PROMPT';
export const EVENT_SET_PROMPT = 'EVENT_SET_PROMPT';

export const EVENT_RAISE_EXCEPTION = 'EVENT_RAISE_EXCEPTION';

export const EVENT_REQUEST_TRANSLATION = 'EVENT_REQUEST_TRANSLATION'; // 번역 데이터 요청
export const EVENT_TRANSLATION = 'EVENT_TRANSLATION'; // 번역 완료

export const EVENT_GOOGLE_TRANSLATION = 'EVENT_GOOGLE_TRANSLATION';
export const EVENT_BATCH_GOOGLE_TRANSLATION = 'EVENT_BATCH_GOOGLE_TRANSLATION';
export const EVENT_CHATGPT_TRANSLATION = 'EVENT_CHATGPT_TRANSLATION';

export const EVENT_GET_LOCAL_CACHE = 'EVENT_GET_LOCAL_CACHE';
export const EVENT_SET_LOCAL_CACHE = 'EVENT_SET_LOCAL_CACHE';
export const EVENT_GET_TRANSLATE_CACHE = 'EVENT_GET_TRANSLATE_CACHE';
export const EVENT_SET_TRANSLATE_CACHE = 'EVENT_SET_TRANSLATE_CACHE';

export const EVENT_DETECT_LANGUAGE = 'EVENT_DETECT_LANGUAGE';
export const EVENT_GET_TRANSLATION_PROMPT = 'EVENT_GET_TRANSLATION_PROMPT';

export const EVENT_CLEAR_QUEUE = 'EVENT_CLEAR_QUEUE';

// chat gpt events
export const EVENT_CONVERSATIONS = 'EVENT_CONVERSATIONS';
export const EVENT_CONVERSATION_UPDATE_TITLE = 'EVENT_CONVERSATION_UPDATE_TITLE';
export const EVENT_CONVERSATION_DELETE = 'EVENT_CONVERSATION_DELETE';
export const EVENT_CONVERSATION = 'EVENT_CONVERSATION';
export const EVENT_MESSAGE_FEEDBACK = 'EVENT_MESSAGE_FEEDBACK';
export const EVENT_GET_MODEL_LIST = 'EVENT_GET_MODEL_LIST';
export const EVENT_CLEAR_ALL_CONVERSATIONS = 'EVENT_CLEAR_ALL_CONVERSATIONS';
export const EVENT_STOP_CONVERSATION = 'EVENT_STOP_CONVERSATION';
export const EVENT_GENERATE_TITLE = 'EVENT_GENERATE_TITLE';
export const EVENT_LOGIN_CHAT_GPT = 'EVENT_LOGIN_CHAT_GPT';

export const EVENT_SET_DEEPL_TRANSLATION = 'EVENT_SET_DEEPL_TRANSLATION';
export const EVENT_GET_TRANSLATION = 'EVENT_GET_TRANSLATION';

export const EVENT_SEARCH_EXTENSION = 'EVENT_SEARCH_EXTENSION';

export const EVENT_API_EXCEPTION = 'EVENT_API_EXCEPTION';
export const EVENT_RESET_HOME = 'EVENT_RESET_HOME';
